version: '2'

services:

  web:
    container_name: 'coredeploy'
    image: 'coredeploy'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5000:5000"

  web2:
    container_name: 'coredeploy2'
    image: 'coredeploy'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5001:5000"
